/*
22 Novembre 
Simona Bronevitsky 11316059 Yihan Hu 11330613 Jules Lemee 11303810
Le projet consiste à créer et exécuter des requêtes sur la base de données du SPVM pour analyser 
les données d'interventions et générer des rapports. Cela permet d'identifier des tendances, 
d'optimiser la prise de décision, et d'améliorer la gestion des ressources.
*/

DROP DATABASE IF EXISTS SPVM;
CREATE DATABASE SPVM;

USE SPVM;

DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE
(
    ID_GENRE INT PRIMARY KEY,
    CODE INT NOT NULL,
    DÉSIGNATION NVARCHAR(50) NOT NULL,
    SALUTATION NVARCHAR(50),
    ABRÉVIATION NVARCHAR(50)
);

DROP TABLE IF EXISTS POSTE_DE_QUARTIER;
CREATE TABLE POSTE_DE_QUARTIER
(
    ID_PDQ NVARCHAR(50) PRIMARY KEY,
    ID_ADDRESSE NVARCHAR(50) FOREIGN KEY REFERENCES ADDRESS(ID_ADDRESSE)
);

DROP TABLE IF EXISTS COUVERTURE;
CREATE TABLE COUVERTURE
(
    ID_COUVERTURE NVARCHAR(50) PRIMARY KEY,
    ID_PDQ NVARCHAR(50) FOREIGN KEY REFERENCES POSTE_DE_QUARTIER(ID_PDQ),
    NOM NVARCHAR(50) NOT NULL    
);

DROP TABLE IF EXISTS AGENT;
CREATE TABLE AGENT
(
    MATRICULE INT PRIMARY KEY,
    GENRE INT  NOT NULL FOREIGN KEY REFERENCES GENRE(ID_GENRE),
    PRÉNOM NVARCHAR(50) NOT NULL,
    NOM NVARCHAR(50) NOT NULL,
    PDQ NVARCHAR(50) NOT NULL FOREIGN KEY REFERENCES POSTE_DE_QUARTIER(ID_PDQ),
);

DROP TABLE IF EXISTS INTERVENTION_AGENT;
CREATE TABLE INVERVENTION_AGENT
(
    MATRICULE_AGENT INT PRIMARY KEY REFERENCES AGENT(MATRICULE),
    ID_INTERVENTION INT PRIMARY KEY REFERENCES INTERVENTION(ID_INTERVENTION),
    EST_RAPPORTEUR NVARCHAR(50)
);

DROP TABLE IF EXISTS INTERVENTION;
CREATE TABLE INTERVENTION
(
    ID_INTERVENTION INT PRIMARY KEY
    ID_CATÉGORIE INT NOT NULL FOREIGN KEY REFERENCES CATÉGORIE_INTERVENTION(ID),
    DATE_INCIDENT DATE NOT NULL,
    ID_QUART_TRAVAIL INT NOT NULL FOREIGN KEY REFERENCES QUART_TRAVAIL(ID)
);

