DROP TABLE IF EXISTS QUARTIER;
CREATE TABLE QUARTIER 
( 
    NUM_QUARTIER INT PRIMARY KEY REFERENCES COUVERTURE(ID_COUVERTURE),
    ID_DIVISION INT NOT NULL FOREIGN KEY REFERENCES DIVISION_ADMINISTRATIVE(ID_DIVISION) ,
    NB_LOGEMENTS INT,
);

DROP TABLE IF EXISTS DIVISION_ADMINISTRATIVE;
CREATE TABLE DIVISION_ADMINISTRATIVE 
(
    ID_DIVISION INT PRIMARY KEY REFERENCES QUARTIER(ID_DIVISION) ,
    ID_ADRESSE INT NOT NULL FOREIGN KEY REFERENCES ADRESSE(ID_ADRESSE),
);

DROP TABLE IF EXISTS VILLE;
CREATE TABLE VILLE
(
    ID_VILLE INT PRIMARY KEY REFERENCES DIVISION_ADMINISTRATIVE(ID_DIVISION),
    POPULATION INT NOT NULL,
    NB_LOGEMENTS INT,
    SUPERFICIE_TERRESTRE FLOAT NOT NULL,
);

DROP TABLE IF EXISTS ARRONDISSEMENT;
CREATE TABLE ARRONDISSEMENT 
(
    ID_ARONDISSEMENT INT PRIMARY KEY REFERENCES DIVISION_ADMINISTRATIVE(ID_DIVISION),
    ID_VILLE INT NOT NULL FOREIGN KEY REFERENCES VILLE(ID_VILLE),
    PERIMETRE FLOAT,
    SUPERFICIE FLOAT,
);



DROP TABLE IF EXISTS ENTITE;
CREATE TABLE ENTITE 
(
    ID_ENTITE INT PRIMARY KEY  REFERENCES DIVISION_ADMINISTRATIVE(ID_DIVISION),
    ID_VILLE INT  NOT NULL FOREIGN KEY REFERENCES VILLE(ID_VILLE),
    DESCRIPTION NVARCHAR(100) NOT NULL,
    NOM_CODE NVARCHAR(50) NOT NULL,
);

